---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 86159.
--- DateTime: 2019/10/12 14:12
---
return {
    no_consumer = true,
    fields = {
        redis_host = { type = "string", required = true, default = "127.0.0.1", },
        redis_port = { type = "number", default = 6379 },
        redis_password = { type = "string" },
        redis_timeout = { type = "number", default = 2000 }
    }
}